export type RightmoveListingDetail = {
    id: any;
    url: string;
    price: number | null;
    currency: string | null;
    bedrooms: number | null;
    bathrooms: number | null;
    address: string | null;
    description: string | null;
    propertyType: string | null;
    propertySubType: string | null;
    agentName: string | null;
    agentBranch: string | null;
    firstVisibleDate: string | null;
    images: string[];
    floorplans: string[];
    postcode: string | null;
    latitude: number | null;
    longitude: number | null;
    tenureType: string | null;
    yearsRemainingOnLease: number | null;
    annualServiceCharge: number | null;
    annualGroundRent: number | null;
    groundRentReviewPeriodYears: number | null;
    groundRentPercentageIncrease: number | null;
    councilTaxBand: string | null;
    displaySize: string | null;
    pricePerSqft: string | null;
    floorAreaSqm: number | null;
    floorAreaSqft: number | null;
    keyFeatures: string[];
    listingUpdateReason: string | null;
    listingStatus: string | null;
    tags: string[];
    nearestStations: Array<Record<string, any>>;
    letAvailableDate: string | null;
    priceFrequency: string | null;
    transactionType: string | null;
    raw?: Record<string, any>;
}